run:
  timeout: 10m
  skip-dirs:
    - test

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - megacheck
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  funlen:
    lines: 500
    statements: 300
  lll:
    line-length: 200
  govet:
    check-shadowing: false
  dupl:
    threshold: 1000
  stylecheck:
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
  gocritic:
    disabled-checks:
      - ifElseChain
  gocyclo:
    min-complexity: 50
issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - lll
        - funlen
        - dupl
    - path: modules/gam-processor/internal/pubsub
      linters:
        - dupl
    - path: modules/account-lookup/internal/tool/recaptcha
      linters:
        - gosec